# Generated by Django 4.2.3 on 2023-09-18 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobinfo',
            name='job_designation',
        ),
        migrations.RemoveField(
            model_name='educationinfo',
            name='board',
        ),
        migrations.RemoveField(
            model_name='educationinfo',
            name='group',
        ),
        migrations.RemoveField(
            model_name='educationinfo',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='driving_license_passport',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='e_tin',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='job',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='nid',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='place_of_birth',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='religion',
        ),
        migrations.DeleteModel(
            name='AddressInfo',
        ),
        migrations.DeleteModel(
            name='JobInfo',
        ),
    ]
