# Generated by Django 4.2.3 on 2023-09-18 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_remove_jobinfo_job_designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='marital_status',
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='phone_no',
            field=models.CharField(blank=True, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message="Indian phone number must be entered in the format: '9999999999' or '+91-9999999999'. 10 digits allowed.", regex='^(?:\\+91-?)?\\d{10}$')]),
        ),
    ]
