# Generated by Django 4.2.3 on 2023-09-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_alter_educationinfo_passing_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationinfo',
            name='passing_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='traininginfo',
            name='year',
            field=models.IntegerField(),
        ),
    ]
