# Generated by Django 4.2.3 on 2023-09-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_personalinfo_address_alter_personalinfo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
