# Generated by Django 4.2.3 on 2023-09-19 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_personalinfo_groups_personalinfo_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='password',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='user_permissions',
        ),
    ]
