# Generated by Django 4.2.3 on 2023-09-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_remove_personalinfo_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininginfo',
            name='place',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='traininginfo',
            name='training_name',
            field=models.CharField(max_length=50),
        ),
    ]
