# Generated by Django 4.2.3 on 2023-10-10 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_academicinfo_registration_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardianinfo',
            name='student',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='guardian',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.guardianinfo'),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=705782, unique=True),
        ),
        migrations.AlterField(
            model_name='guardianinfo',
            name='guardian_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='guardianinfo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
