# Generated by Django 4.2.3 on 2023-09-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_academicinfo_registration_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacherpersonalinfo',
            name='user',
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=512627, unique=True),
        ),
    ]
