# Generated by Django 4.2.3 on 2023-09-05 00:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='doj',
            field=models.DateField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+91'. Up to 10 digits allowed.", regex='^\\+?1?\\d{9,10}$')]),
        ),
    ]
