# Generated by Django 4.2.3 on 2023-10-12 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_resource_class_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=238938, unique=True),
        ),
        migrations.CreateModel(
            name='PreistPersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_contact_phone', models.CharField(max_length=15)),
                ('ordination_date', models.DateField()),
                ('diocese', models.CharField(max_length=255)),
                ('previous_parish', models.TextField(blank=True, null=True)),
                ('availability', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
