# Generated by Django 4.2.3 on 2023-09-24 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_remove_personalinfo_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='profile_pic',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='guardianinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherpersonalinfo',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=971973, unique=True),
        ),
    ]
