# Generated by Django 4.2.3 on 2023-09-05 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_resource_alter_student_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='resource_link',
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_pdf',
            field=models.FileField(null=True, upload_to='store/pdfs/'),
        ),
        migrations.AddField(
            model_name='resource',
            name='teacher_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.teacher'),
        ),
    ]
