# Generated by Django 4.2.3 on 2023-09-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_rename_profile_pic_customuser_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=306507, unique=True),
        ),
    ]
