# Generated by Django 4.2.3 on 2023-09-07 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_remove_resource_resource_link_resource_resource_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='father_contact',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+91'. Up to 10 digits allowed.", regex='^\\+?1?\\d{9,10}$')]),
        ),
        migrations.AddField(
            model_name='student',
            name='fathername',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_contact',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+91'. Up to 10 digits allowed.", regex='^\\+?1?\\d{9,10}$')]),
        ),
        migrations.AddField(
            model_name='student',
            name='mothername',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_pdf',
            field=models.FileField(null=True, upload_to='notes/pdfs/'),
        ),
    ]
