# Generated by Django 4.2.3 on 2023-09-28 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_academicinfo_registration_no_studentattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='class_registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.classregistration'),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=357476, unique=True),
        ),
    ]
