# Generated by Django 4.2.3 on 2024-01-16 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_academicinfo_registration_no_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=147214, unique=True),
        ),
        migrations.CreateModel(
            name='ScheduledClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('platform_link', models.URLField()),
                ('enrolled_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.classregistration')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.guideteacher')),
            ],
        ),
    ]
