# Generated by Django 4.2.3 on 2023-09-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_teacher_address_teacher_dob_teacher_doj_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='resource_pdf',
            new_name='resource_file',
        ),
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='file_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='uploaded_date',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
