# Generated by Django 4.2.3 on 2024-01-18 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_alter_academicinfo_registration_no_scheduledclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=238746, unique=True),
        ),
        migrations.CreateModel(
            name='OnlineClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('link', models.URLField()),
                ('description', models.TextField()),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.classregistration')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.guideteacher')),
            ],
        ),
    ]
