# Generated by Django 4.2.3 on 2024-01-18 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_alter_academicinfo_registration_no_onlineclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlineclass',
            name='date_time',
        ),
        migrations.AddField(
            model_name='onlineclass',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlineclass',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=345903, unique=True),
        ),
        migrations.AlterField(
            model_name='onlineclass',
            name='class_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.classregistration'),
        ),
        migrations.AlterField(
            model_name='onlineclass',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onlineclass',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onlineclass',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.guideteacher'),
        ),
    ]
