# Generated by Django 4.2.3 on 2023-09-10 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_remove_student_student_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_number',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+91'. Up to 10 digits allowed.", regex='^\\+?1?\\d{9,110}$')]),
        ),
    ]
