# Generated by Django 4.2.3 on 2024-01-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_remove_onlineclass_date_time_onlineclass_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=995529, unique=True),
        ),
        migrations.AlterField(
            model_name='leavereportstudent',
            name='leave_message',
            field=models.CharField(max_length=255),
        ),
    ]
