# Generated by Django 4.2.3 on 2023-09-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_alter_academicinfo_registration_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentattendance',
            name='is_present',
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=79667, unique=True),
        ),
    ]
