# Generated by Django 4.2.3 on 2023-09-11 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_student_student_number_alter_teacher_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('display_name', models.CharField(max_length=10, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
