# Generated by Django 4.2.3 on 2023-09-11 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_class_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.teacher')),
            ],
        ),
    ]
