# Generated by Django 4.2.3 on 2024-01-29 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_alter_academicinfo_registration_no_counselingsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=838861, unique=True),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_file', models.FileField(upload_to='certificates/')),
                ('issue_date', models.DateField()),
                ('is_previous_class', models.BooleanField(default=False)),
                ('class_associated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.classregistration')),
                ('enrolled_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.enrolledstudent')),
            ],
        ),
    ]
