# Generated by Django 4.2.3 on 2023-09-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_guideteacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(unique=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
