# Generated by Django 4.2.3 on 2023-10-03 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_attendance_attendancereport_leavereportstaff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=967644, unique=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='ClassInfo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school.enrolledstudent'),
        ),
    ]
