# Generated by Django 4.2.3 on 2023-09-11 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('class_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.class')),
                ('guide_teacher', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.guideteacher')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.section')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.session')),
            ],
            options={
                'unique_together': {('class_name', 'section', 'guide_teacher')},
            },
        ),
    ]
