# Generated by Django 4.2.3 on 2023-09-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_classregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='uploaded_date',
            field=models.DateField(max_length=30, null=True),
        ),
    ]
