# Generated by Django 4.2.3 on 2023-09-11 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_alter_resource_uploaded_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='teacher_number',
            new_name='name',
        ),
    ]
