# Generated by Django 4.2.3 on 2023-10-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_alter_academicinfo_registration_no_teachernotice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=636459, unique=True),
        ),
    ]
