# Generated by Django 4.2.3 on 2023-09-11 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_rename_teacher_number_resource_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='name',
            new_name='teacher_name',
        ),
    ]
