# Generated by Django 4.2.3 on 2023-10-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_alter_academicinfo_registration_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=119743, unique=True),
        ),
        migrations.AlterField(
            model_name='leavereportstudent',
            name='leave_date',
            field=models.DateField(null=True),
        ),
    ]
