# Generated by Django 4.2.3 on 2024-02-05 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_mark_class_name_alter_academicinfo_registration_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='class_name',
        ),
        migrations.AddField(
            model_name='mark',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.classregistration'),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=953776, unique=True),
        ),
    ]
