# Generated by Django 4.2.3 on 2024-02-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_remove_mark_class_name_mark_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='name',
            new_name='class_name',
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=284909, unique=True),
        ),
    ]
