# Generated by Django 4.2.3 on 2024-02-05 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_rename_name_mark_class_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=932481, unique=True),
        ),
    ]
