# Generated by Django 4.2.3 on 2023-10-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_alter_academicinfo_registration_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=819342, unique=True),
        ),
    ]
