# Generated by Django 4.2.3 on 2023-10-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0024_alter_academicinfo_registration_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teachernotice',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=310115, unique=True),
        ),
    ]
