# Generated by Django 4.2.3 on 2023-09-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0024_alter_academicinfo_registration_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=264094, unique=True),
        ),
    ]
