# Generated by Django 4.2.3 on 2023-09-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0025_alter_academicinfo_registration_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideteacher',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=329921, unique=True),
        ),
    ]
