# Generated by Django 4.2.3 on 2023-10-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0025_notice_title_teachernotice_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teachernotice',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=618590, unique=True),
        ),
    ]
