# Generated by Django 4.2.3 on 2023-09-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0026_guideteacher_is_deleted_session_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=908576, unique=True),
        ),
    ]
