# Generated by Django 4.2.3 on 2023-10-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0026_notice_is_read_teachernotice_is_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=89147, unique=True),
        ),
    ]
