# Generated by Django 4.2.3 on 2023-09-18 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0027_section_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=674478, unique=True),
        ),
    ]
