# Generated by Django 4.2.3 on 2023-10-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0027_alter_academicinfo_registration_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=432152, unique=True),
        ),
    ]
