# Generated by Django 4.2.3 on 2023-09-18 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_remove_jobinfo_job_designation_and_more'),
        ('school', '0029_alter_academicinfo_registration_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=618297, unique=True),
        ),
        migrations.AlterField(
            model_name='guideteacher',
            name='name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.personalinfo'),
        ),
    ]
