# Generated by Django 4.2.3 on 2024-02-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0029_alter_academicinfo_registration_no_onlineexam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=62415, unique=True),
        ),
    ]
