# Generated by Django 4.2.3 on 2024-02-19 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0032_academicinfo_user_alter_academicinfo_registration_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='exam_schedule',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='selected_option',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='studentexamsubmission',
            name='exam_schedule',
        ),
        migrations.RemoveField(
            model_name='studentexamsubmission',
            name='student',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='ClassInfo_id',
        ),
        migrations.AddField(
            model_name='attendance',
            name='class_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school.classinfo'),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=820323, unique=True),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='StudentAnswer',
        ),
        migrations.DeleteModel(
            name='StudentExamSubmission',
        ),
    ]
