# Generated by Django 4.2.3 on 2024-02-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0033_remove_question_exam_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=245418, unique=True),
        ),
    ]
