# Generated by Django 4.2.3 on 2023-09-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0035_alter_academicinfo_registration_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='birth_certificate_no',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='religion',
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=368360, unique=True),
        ),
    ]
