# Generated by Django 4.2.3 on 2023-09-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0036_remove_personalinfo_birth_certificate_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentaddressinfo',
            name='district',
        ),
        migrations.RemoveField(
            model_name='studentaddressinfo',
            name='union',
        ),
        migrations.RemoveField(
            model_name='studentaddressinfo',
            name='upazilla',
        ),
        migrations.RemoveField(
            model_name='union',
            name='district',
        ),
        migrations.RemoveField(
            model_name='union',
            name='upazilla',
        ),
        migrations.RemoveField(
            model_name='upazilla',
            name='district',
        ),
        migrations.RemoveField(
            model_name='academicinfo',
            name='address_info',
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=81559, unique=True),
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='StudentAddressInfo',
        ),
        migrations.DeleteModel(
            name='Union',
        ),
        migrations.DeleteModel(
            name='Upazilla',
        ),
    ]
