# Generated by Django 4.2.3 on 2023-09-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0037_remove_studentaddressinfo_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardianinfo',
            name='father_occupation',
        ),
        migrations.RemoveField(
            model_name='guardianinfo',
            name='father_yearly_income',
        ),
        migrations.RemoveField(
            model_name='guardianinfo',
            name='mother_occupation',
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=357713, unique=True),
        ),
        migrations.AlterField(
            model_name='guardianinfo',
            name='father_phone_no',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='guardianinfo',
            name='guardian_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='guardianinfo',
            name='guardian_phone_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='guardianinfo',
            name='mother_phone_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
