# Generated by Django 5.0.3 on 2024-03-19 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0037_alter_academicinfo_registration_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicinfo',
            name='academic_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.session'),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=74195, unique=True),
        ),
    ]
