# Generated by Django 4.2.3 on 2023-09-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0038_remove_guardianinfo_father_occupation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previousacademiccertificate',
            name='birth_certificate',
        ),
        migrations.RemoveField(
            model_name='previousacademiccertificate',
            name='release_letter',
        ),
        migrations.RemoveField(
            model_name='previousacademiccertificate',
            name='stipen_certificate',
        ),
        migrations.RemoveField(
            model_name='previousacademiccertificate',
            name='testimonial',
        ),
        migrations.RemoveField(
            model_name='previousacademicinfo',
            name='gpa',
        ),
        migrations.RemoveField(
            model_name='previousacademicinfo',
            name='group',
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=506553, unique=True),
        ),
        migrations.AlterField(
            model_name='previousacademicinfo',
            name='passing_year',
            field=models.DateField(),
        ),
    ]
