# Generated by Django 4.2.3 on 2023-09-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0039_remove_previousacademiccertificate_birth_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=534125, unique=True),
        ),
        migrations.AlterField(
            model_name='previousacademicinfo',
            name='passing_year',
            field=models.CharField(max_length=4),
        ),
    ]
