# Generated by Django 4.2.3 on 2023-09-18 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_personalinfo_date_of_birth'),
        ('school', '0040_alter_academicinfo_registration_no_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=113350, unique=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='teacher_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.personalinfo'),
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
