# Generated by Django 4.2.3 on 2023-09-19 01:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('school', '0042_alter_academicinfo_registration_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='personalinfo_set', related_query_name='personalinfo', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='password',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='personalinfo_set', related_query_name='personalinfo', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=536137, unique=True),
        ),
    ]
