# Generated by Django 4.2.3 on 2023-09-19 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_personalinfo_date_of_birth'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('school', '0043_personalinfo_groups_personalinfo_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=651682, unique=True),
        ),
        migrations.AlterField(
            model_name='guideteacher',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.personalinfo'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='student_personalinfo_set', related_query_name='student_personalinfo', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='student_personalinfo_permissions_set', related_query_name='student_personalinfo_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='teacher_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.personalinfo'),
        ),
    ]
