# Generated by Django 4.2.3 on 2023-09-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0044_alter_academicinfo_registration_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='password',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=589457, unique=True),
        ),
    ]
