# Generated by Django 4.2.3 on 2023-09-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0045_remove_personalinfo_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=3844, unique=True),
        ),
    ]
