# Generated by Django 4.2.3 on 2023-09-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0047_alter_academicinfo_registration_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=781210, unique=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='display_name',
            field=models.CharField(max_length=10),
        ),
    ]
