# Generated by Django 4.2.3 on 2023-09-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0048_alter_academicinfo_registration_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=128656, unique=True),
        ),
        migrations.AlterField(
            model_name='classregistration',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
