# Generated by Django 4.2.3 on 2023-09-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0050_alter_academicinfo_registration_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=368635, unique=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='uploaded_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
