# Generated by Django 4.2.3 on 2024-03-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='ending_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='name_column',
        ),
        migrations.RemoveField(
            model_name='event',
            name='org_column',
        ),
        migrations.RemoveField(
            model_name='event',
            name='starting_date',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='name',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='org',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='subject',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
